# Generated by Django 4.0.4 on 2022-05-25 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='descripcionComentario',
            field=models.CharField(max_length=100, verbose_name='Descripcion del comentario'),
        ),
        migrations.AlterField(
            model_name='comuna',
            name='descripcionComuna',
            field=models.CharField(max_length=100, verbose_name='Descripcion de la comuna'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='descripcionDireccion',
            field=models.CharField(max_length=100, verbose_name='Descripcion de la direccion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcionProducto',
            field=models.CharField(max_length=100, verbose_name='Descripcion del producto'),
        ),
    ]
