# Generated by Django 4.0.4 on 2022-06-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcionProducto',
            field=models.CharField(max_length=300, verbose_name='Descripcion del producto'),
        ),
    ]
