# Generated by Django 4.0.4 on 2022-06-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_producto_descripcionproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='status',
            field=models.IntegerField(blank=True, null=True, verbose_name='Estatus de la venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fVenta',
            field=models.DateField(auto_now=True, verbose_name='fecha venta'),
        ),
    ]
